// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user_matching

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MatcherClient is the client API for Matcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatcherClient interface {
	GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesReply, error)
}

type matcherClient struct {
	cc grpc.ClientConnInterface
}

func NewMatcherClient(cc grpc.ClientConnInterface) MatcherClient {
	return &matcherClient{cc}
}

var matcherGetMatchesStreamDesc = &grpc.StreamDesc{
	StreamName: "GetMatches",
}

func (c *matcherClient) GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesReply, error) {
	out := new(GetMatchesReply)
	err := c.cc.Invoke(ctx, "/Matcher/GetMatches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatcherService is the service API for Matcher service.
// Fields should be assigned to their respective handler implementations only before
// RegisterMatcherService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type MatcherService struct {
	GetMatches func(context.Context, *GetMatchesRequest) (*GetMatchesReply, error)
}

func (s *MatcherService) getMatches(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GetMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Matcher/GetMatches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetMatches(ctx, req.(*GetMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterMatcherService registers a service implementation with a gRPC server.
func RegisterMatcherService(s grpc.ServiceRegistrar, srv *MatcherService) {
	srvCopy := *srv
	if srvCopy.GetMatches == nil {
		srvCopy.GetMatches = func(context.Context, *GetMatchesRequest) (*GetMatchesReply, error) {
			return nil, status.Errorf(codes.Unimplemented, "method GetMatches not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "Matcher",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "GetMatches",
				Handler:    srvCopy.getMatches,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "user_matching.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewMatcherService creates a new MatcherService containing the
// implemented methods of the Matcher service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewMatcherService(s interface{}) *MatcherService {
	ns := &MatcherService{}
	if h, ok := s.(interface {
		GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesReply, error)
	}); ok {
		ns.GetMatches = h.GetMatches
	}
	return ns
}

// UnstableMatcherService is the service API for Matcher service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableMatcherService interface {
	GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesReply, error)
}
